# Stage for building the application
FROM node:22-alpine as build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available) for dependency installation
COPY package*.json ./ 

# Install dependencies
RUN npm install 

# Copy the rest of the project files
COPY . .

# Build the frontend
RUN npm run build 

# Stage for deployment using Nginx
FROM nginx:stable-alpine

# Copy the built files from the build stage to the Nginx directory
COPY --from=build /app/dist /usr/share/nginx/html

# Copy the Nginx configuration file
COPY --from=build /app/nginx.conf /etc/nginx/nginx.conf

# Expose port 5173 for Nginx
EXPOSE 5173

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
